package com.tabela.accounting.enums;

public enum TransactionSource
{
  BANK_TRANSACTION,  MILK_SALE,  MILK_PURCHASE,  ANIMAL_PURCHASE,  ANIMAL_SALE,  CATTLEFEED_PURCHASE,  GRASS_PURCHASE,  CATTLEFEED_SALE,  TABELA_RENT,  MEDICAL_PURCHASE,  OTHER_MILK,  LABOUR,  EXPENSE,  OTHER,  LOAN,  OTHER_PURCHASE,  SALVAGE_EXP,  CONSTRUCTION_WORK,  ELECTRICITY_EXP,  FREIGHT_PAID,  HELL_CHARGES,  BREEDING,  CATTLEFEED_BREEDING,  CHEEK,  CURD,  CREAM,  PANEER,  DAIRY_EXP,  CONVEYANCE_TRAVELLING,  ROOM_RENT,  PRINTING_STATIONARY,  TELEPHONE_EXP,  TRANSPORTATION_EXP,  TRAVELLING_EXP,  DIWALI,  MEDICAL_EXP,  TABELA_GENERAL;
}
