package com.tabela.accounting.enums;

public enum MerchantType
{
  ANIMAL_SALE,  ANIMAL_PURCHASE,  CATTLEFEED,  GRASS,  TABELA_RENT,  ROOM_RENT,  BREEDING,  CATTLEFEED_BREEDING,  MEDICAL_PURCHASE,  OTHER_PURCHASE,  OTHER_MILK;
}
